version: '3.8'

services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.app
      args:
        UID: ${UID:-1001}
        GID: ${GID:-1001}
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./dockerfiles/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - laravel
    command: sh -c "composer install && php-fpm"

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - ./app:/var/www/html
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    ports:
      - "${DB_PORT:-33060}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-sail}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secret}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USERNAME}", "-p${DB_PASSWORD}"]
      timeout: 20s
      retries: 10
      start_period: 5s

  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    #ports:
      #- "${PHPMYADMIN_PORT:-8080}:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USERNAME:-sail}
      PMA_PASSWORD: ${DB_PASSWORD:-password}
      PMA_ABSOLUTE_URI: http://localhost:807/togetku/
    depends_on:
      - db
    networks:
      - laravel

  node:
    image: node:18-alpine
    container_name: laravel_node
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    command: sh -c "npm install && npm run build"
    ports:
      - "${VITE_PORT:-5173}:5173"
    networks:
      - laravel

volumes:
  db_data:
  redis_data:

networks:
  laravel:
    driver: bridge
